### ISSUE TITLE
Calendar’s weekdays are broken

### ISSUE THREAD

**Issue by nandorojo** [web-ridge/react-native-paper-dates#53]
This is a very urgent bug. The weekdays at the top of the calendar are incorrect, rendering the calendar a bit useless.

![image](https://user-images.githubusercontent.com/13172299/110209889-eb050d80-7e5c-11eb-852f-b09b05bbbf3d.png)

Notice the highlighted day in the photo. It says Friday March 6th. But today is _Saturday_ March 6th. Calendars (at least in the US) typically start with a Sunday, so maybe that explains the problem.

Compare with the correct dates from iPhone Calendar:

![image](https://user-images.githubusercontent.com/13172299/110210053-d83f0880-7e5d-11eb-8013-b34dc863e67d.png)

I have users trying to select dates based on weekdays, and they're choosing the wrong one.

The problem happens on nearly every month. You can see it on the example app: https://www.reactnativepaperdates.com/

Compare it to a calendar and you'll see that the days are wrong.

@RichardLindhout please tell me if I can help solve this somehow. It's really important this gets fixed in order to keep using the library. Thank you!

**Comment by RichardLindhout** [comment]
Really strange looks like a difference in locale / timezone

**Comment by RichardLindhout** [comment]
<img width="673" alt="Schermafbeelding 2021-03-06 om 18 29 41" src="https://user-images.githubusercontent.com/6492229/110215410-f29ed380-7ea9-11eb-944b-c39e9852a499.png">

**Comment by RichardLindhout** [comment]
Oke I think I fixed it. Let me release a new version

**Comment by RichardLindhout** [comment]
Let me know if this fixed your issue. I think it does since it works for me but it created the weekdays in dutch format and it could break on some devices I guess

**Comment by nandorojo** [comment]
Is the example app site updated too? I still have the issue there.

**Comment by RichardLindhout** [comment]
No, I'll update it

**Comment by RichardLindhout** [comment]
<img width="538" alt="Schermafbeelding 2021-03-06 om 19 09 28" src="https://user-images.githubusercontent.com/6492229/110216447-87f09680-7eaf-11eb-97d6-1d9c01404a55.png">
Updated version online, should show Example version: 0.3.2

**Comment by nandorojo** [comment]
I think that did it! Thanks :)
